name: breast-cancer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.1.3
  - pandas=2.3.0
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - scikit-learn=1.7.0
  - joblib=1.5.1
  - jupyter=1.1.1
  - pip=25.1.1
  - pip:
    - ipykernel